### ISSUE TITLE
about data/eeg_data.csv and data/target.csv

### ISSUE THREAD

**Issue by JJFORJEY** [tbary/MasterThesis#1]
Hi, I am interesting in your experiment.
However, after applying to the dataset, I found that there is no such thing as EEF_DATA. CSV and target.csv data files.

**Comment by tbary** [comment]
Hi @JJFORJEY !
First of all, thanks for the interest you have in this project.
The dataset you mentionned is indeed missing, as it is the property of the UCLouvain university...
If you wish to obtain a personnal copy, please contact me on my work email (tim.bary@uclouvain.be). 
Nonetheless, I would recommend to work with the wider dataset from the Temple University Seizure Detection Corpus (TUSZ). It is possible to ask for this dataset by filling a form a this address: https://isip.piconepress.com/projects/nedc/html/tuh_eeg/
I will update the readme file to make this clarification appear.
All the best,
Tim

**Comment by tbary** [comment]
The readme file has been updated with the relevant information. Closing this issue...
Please, feel free to contact me if you need any further information.
